require 'opal'

require 'opal/rails/errors'
require 'opal/rails/entrypoints_resolver'
require 'opal/rails/builder_runner'
require 'opal/rails/outputs_manifest'
require 'opal/rails/path_setup'
require 'opal/rails/task_hooks'
require 'opal/rails/engine'
require 'opal/rails/template_handler'
require 'opal/rails/version'
